provider: github
major-version: 6
esc:
    enabled: true
env:
    GH_ORGANIZATION: ${{ secrets.GH_ORGANIZATION }}
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    GH_TESTING_TOKEN: ${{ secrets.GH_TESTING_TOKEN }}
makeTemplate: bridged
pulumiConvert: 1
registryDocs: true
