provider: github
major-version: 6
env:
  GH_ORGANIZATION: ${{ secrets.GH_ORGANIZATION }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_TESTING_TOKEN: ${{ secrets.GH_TESTING_TOKEN }}
makeTemplate: bridged
plugins:
  - name: std
    version: "1.6.2"

  - name: terraform
    version: "1.0.16"
    kind: converter

  - name: tls
    version: "5.0.1"
pulumiConvert: 1
