[[override]]
  name = "github.com/google/go-github"
  revision = "5f3187e17912ee2e3fbe2fa5bdada9d577d25e83"

[[override]]
  name = "github.com/pulumi/pulumi"
  revision = "1dbe4b7dfd59a8e045bf07b423aa73d2f457c3ca"

[[override]]
  name = "github.com/pulumi/pulumi-terraform"
  revision = "4057f2ea47decc79726c6142c5ce2b0c1abff0bb"

[[override]]
  name = "github.com/hashicorp/terraform"
  source = "github.com/pulumi/terraform"
  branch = "pulumi-master"
