// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Github
{
    /// <summary>
    /// This resource allows you to create and manage IP allow list entries for a GitHub Enterprise account. IP allow list entries define IP addresses or ranges that are permitted to access private resources in the enterprise.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Github = Pulumi.Github;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var test = new Github.Index.EnterpriseIpAllowListEntry("test", new()
    ///     {
    ///         EnterpriseSlug = "my-enterprise",
    ///         Ip = "192.168.1.0/20",
    ///         Name = "My IP Range Name",
    ///         IsActive = true,
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// This resource can be imported using the ID of the IP allow list entry:
    /// 
    /// ```sh
    /// $ pulumi import github:index/enterpriseIpAllowListEntry:EnterpriseIpAllowListEntry test IALE_kwHOC1234567890a
    /// ```
    /// </summary>
    [GithubResourceType("github:index/enterpriseIpAllowListEntry:EnterpriseIpAllowListEntry")]
    public partial class EnterpriseIpAllowListEntry : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Timestamp of when the entry was created.
        /// </summary>
        [Output("createdAt")]
        public Output<string> CreatedAt { get; private set; } = null!;

        /// <summary>
        /// The slug of the enterprise.
        /// </summary>
        [Output("enterpriseSlug")]
        public Output<string> EnterpriseSlug { get; private set; } = null!;

        /// <summary>
        /// An IP address or range of IP addresses in CIDR notation.
        /// </summary>
        [Output("ip")]
        public Output<string> Ip { get; private set; } = null!;

        /// <summary>
        /// Whether the entry is currently active. Default: true.
        /// </summary>
        [Output("isActive")]
        public Output<bool?> IsActive { get; private set; } = null!;

        /// <summary>
        /// A descriptive name for the IP allow list entry.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Timestamp of when the entry was last updated.
        /// </summary>
        [Output("updatedAt")]
        public Output<string> UpdatedAt { get; private set; } = null!;


        /// <summary>
        /// Create a EnterpriseIpAllowListEntry resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public EnterpriseIpAllowListEntry(string name, EnterpriseIpAllowListEntryArgs args, CustomResourceOptions? options = null)
            : base("github:index/enterpriseIpAllowListEntry:EnterpriseIpAllowListEntry", name, args ?? new EnterpriseIpAllowListEntryArgs(), MakeResourceOptions(options, ""))
        {
        }

        private EnterpriseIpAllowListEntry(string name, Input<string> id, EnterpriseIpAllowListEntryState? state = null, CustomResourceOptions? options = null)
            : base("github:index/enterpriseIpAllowListEntry:EnterpriseIpAllowListEntry", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing EnterpriseIpAllowListEntry resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static EnterpriseIpAllowListEntry Get(string name, Input<string> id, EnterpriseIpAllowListEntryState? state = null, CustomResourceOptions? options = null)
        {
            return new EnterpriseIpAllowListEntry(name, id, state, options);
        }
    }

    public sealed class EnterpriseIpAllowListEntryArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The slug of the enterprise.
        /// </summary>
        [Input("enterpriseSlug", required: true)]
        public Input<string> EnterpriseSlug { get; set; } = null!;

        /// <summary>
        /// An IP address or range of IP addresses in CIDR notation.
        /// </summary>
        [Input("ip", required: true)]
        public Input<string> Ip { get; set; } = null!;

        /// <summary>
        /// Whether the entry is currently active. Default: true.
        /// </summary>
        [Input("isActive")]
        public Input<bool>? IsActive { get; set; }

        /// <summary>
        /// A descriptive name for the IP allow list entry.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public EnterpriseIpAllowListEntryArgs()
        {
        }
        public static new EnterpriseIpAllowListEntryArgs Empty => new EnterpriseIpAllowListEntryArgs();
    }

    public sealed class EnterpriseIpAllowListEntryState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Timestamp of when the entry was created.
        /// </summary>
        [Input("createdAt")]
        public Input<string>? CreatedAt { get; set; }

        /// <summary>
        /// The slug of the enterprise.
        /// </summary>
        [Input("enterpriseSlug")]
        public Input<string>? EnterpriseSlug { get; set; }

        /// <summary>
        /// An IP address or range of IP addresses in CIDR notation.
        /// </summary>
        [Input("ip")]
        public Input<string>? Ip { get; set; }

        /// <summary>
        /// Whether the entry is currently active. Default: true.
        /// </summary>
        [Input("isActive")]
        public Input<bool>? IsActive { get; set; }

        /// <summary>
        /// A descriptive name for the IP allow list entry.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Timestamp of when the entry was last updated.
        /// </summary>
        [Input("updatedAt")]
        public Input<string>? UpdatedAt { get; set; }

        public EnterpriseIpAllowListEntryState()
        {
        }
        public static new EnterpriseIpAllowListEntryState Empty => new EnterpriseIpAllowListEntryState();
    }
}
