// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Github
{
    /// <summary>
    /// This resource allows you to manage code security and analysis settings for a GitHub Enterprise account. This controls Advanced Security, Secret Scanning, and related security features that are automatically enabled for new repositories in the enterprise.
    /// 
    /// You must have enterprise admin access to use this resource.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Github = Pulumi.Github;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     // Basic security settings - enable secret scanning only
    ///     var basic = new Github.EnterpriseSecurityAnalysisSettings("basic", new()
    ///     {
    ///         EnterpriseSlug = "my-enterprise",
    ///         SecretScanningEnabledForNewRepositories = true,
    ///     });
    /// 
    ///     // Full security configuration with all features enabled
    ///     var comprehensive = new Github.EnterpriseSecurityAnalysisSettings("comprehensive", new()
    ///     {
    ///         EnterpriseSlug = "my-enterprise",
    ///         AdvancedSecurityEnabledForNewRepositories = true,
    ///         SecretScanningEnabledForNewRepositories = true,
    ///         SecretScanningPushProtectionEnabledForNewRepositories = true,
    ///         SecretScanningValidityChecksEnabled = true,
    ///         SecretScanningPushProtectionCustomLink = "https://octokit.com/security-guidelines",
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Notes
    /// 
    /// &gt; **Note:** This resource requires a GitHub Enterprise account and enterprise admin permissions.
    /// 
    /// &gt; **Note:** Advanced Security features require a GitHub Advanced Security license.
    /// 
    /// When this resource is destroyed, all security analysis settings will be reset to disabled defaults for security reasons.
    /// 
    /// ## Dependencies
    /// 
    /// This resource manages the following security features:
    /// 
    /// - **Advanced Security**: Code scanning, secret scanning, and dependency review
    /// - **Secret Scanning**: Automatic detection of secrets in code
    /// - **Push Protection**: Prevents secrets from being committed to repositories
    /// - **Validity Checks**: Verifies that detected secrets are actually valid
    /// 
    /// These settings only apply to **new repositories** created after the settings are enabled. Existing repositories are not affected and must be configured individually.
    /// 
    /// ## Import
    /// 
    /// Enterprise security analysis settings can be imported using the enterprise slug:
    /// 
    /// ```sh
    /// $ pulumi import github:index/enterpriseSecurityAnalysisSettings:EnterpriseSecurityAnalysisSettings example my-enterprise
    /// ```
    /// </summary>
    [GithubResourceType("github:index/enterpriseSecurityAnalysisSettings:EnterpriseSecurityAnalysisSettings")]
    public partial class EnterpriseSecurityAnalysisSettings : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Whether GitHub Advanced Security is automatically enabled for new repositories. Defaults to `False`. Requires Advanced Security license.
        /// </summary>
        [Output("advancedSecurityEnabledForNewRepositories")]
        public Output<bool?> AdvancedSecurityEnabledForNewRepositories { get; private set; } = null!;

        /// <summary>
        /// The slug of the enterprise.
        /// </summary>
        [Output("enterpriseSlug")]
        public Output<string> EnterpriseSlug { get; private set; } = null!;

        /// <summary>
        /// Whether secret scanning is automatically enabled for new repositories. Defaults to `False`.
        /// </summary>
        [Output("secretScanningEnabledForNewRepositories")]
        public Output<bool?> SecretScanningEnabledForNewRepositories { get; private set; } = null!;

        /// <summary>
        /// Custom URL for secret scanning push protection bypass instructions.
        /// </summary>
        [Output("secretScanningPushProtectionCustomLink")]
        public Output<string?> SecretScanningPushProtectionCustomLink { get; private set; } = null!;

        /// <summary>
        /// Whether secret scanning push protection is automatically enabled for new repositories. Defaults to `False`.
        /// </summary>
        [Output("secretScanningPushProtectionEnabledForNewRepositories")]
        public Output<bool?> SecretScanningPushProtectionEnabledForNewRepositories { get; private set; } = null!;

        /// <summary>
        /// Whether secret scanning validity checks are enabled. Defaults to `False`.
        /// </summary>
        [Output("secretScanningValidityChecksEnabled")]
        public Output<bool?> SecretScanningValidityChecksEnabled { get; private set; } = null!;


        /// <summary>
        /// Create a EnterpriseSecurityAnalysisSettings resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public EnterpriseSecurityAnalysisSettings(string name, EnterpriseSecurityAnalysisSettingsArgs args, CustomResourceOptions? options = null)
            : base("github:index/enterpriseSecurityAnalysisSettings:EnterpriseSecurityAnalysisSettings", name, args ?? new EnterpriseSecurityAnalysisSettingsArgs(), MakeResourceOptions(options, ""))
        {
        }

        private EnterpriseSecurityAnalysisSettings(string name, Input<string> id, EnterpriseSecurityAnalysisSettingsState? state = null, CustomResourceOptions? options = null)
            : base("github:index/enterpriseSecurityAnalysisSettings:EnterpriseSecurityAnalysisSettings", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing EnterpriseSecurityAnalysisSettings resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static EnterpriseSecurityAnalysisSettings Get(string name, Input<string> id, EnterpriseSecurityAnalysisSettingsState? state = null, CustomResourceOptions? options = null)
        {
            return new EnterpriseSecurityAnalysisSettings(name, id, state, options);
        }
    }

    public sealed class EnterpriseSecurityAnalysisSettingsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether GitHub Advanced Security is automatically enabled for new repositories. Defaults to `False`. Requires Advanced Security license.
        /// </summary>
        [Input("advancedSecurityEnabledForNewRepositories")]
        public Input<bool>? AdvancedSecurityEnabledForNewRepositories { get; set; }

        /// <summary>
        /// The slug of the enterprise.
        /// </summary>
        [Input("enterpriseSlug", required: true)]
        public Input<string> EnterpriseSlug { get; set; } = null!;

        /// <summary>
        /// Whether secret scanning is automatically enabled for new repositories. Defaults to `False`.
        /// </summary>
        [Input("secretScanningEnabledForNewRepositories")]
        public Input<bool>? SecretScanningEnabledForNewRepositories { get; set; }

        /// <summary>
        /// Custom URL for secret scanning push protection bypass instructions.
        /// </summary>
        [Input("secretScanningPushProtectionCustomLink")]
        public Input<string>? SecretScanningPushProtectionCustomLink { get; set; }

        /// <summary>
        /// Whether secret scanning push protection is automatically enabled for new repositories. Defaults to `False`.
        /// </summary>
        [Input("secretScanningPushProtectionEnabledForNewRepositories")]
        public Input<bool>? SecretScanningPushProtectionEnabledForNewRepositories { get; set; }

        /// <summary>
        /// Whether secret scanning validity checks are enabled. Defaults to `False`.
        /// </summary>
        [Input("secretScanningValidityChecksEnabled")]
        public Input<bool>? SecretScanningValidityChecksEnabled { get; set; }

        public EnterpriseSecurityAnalysisSettingsArgs()
        {
        }
        public static new EnterpriseSecurityAnalysisSettingsArgs Empty => new EnterpriseSecurityAnalysisSettingsArgs();
    }

    public sealed class EnterpriseSecurityAnalysisSettingsState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether GitHub Advanced Security is automatically enabled for new repositories. Defaults to `False`. Requires Advanced Security license.
        /// </summary>
        [Input("advancedSecurityEnabledForNewRepositories")]
        public Input<bool>? AdvancedSecurityEnabledForNewRepositories { get; set; }

        /// <summary>
        /// The slug of the enterprise.
        /// </summary>
        [Input("enterpriseSlug")]
        public Input<string>? EnterpriseSlug { get; set; }

        /// <summary>
        /// Whether secret scanning is automatically enabled for new repositories. Defaults to `False`.
        /// </summary>
        [Input("secretScanningEnabledForNewRepositories")]
        public Input<bool>? SecretScanningEnabledForNewRepositories { get; set; }

        /// <summary>
        /// Custom URL for secret scanning push protection bypass instructions.
        /// </summary>
        [Input("secretScanningPushProtectionCustomLink")]
        public Input<string>? SecretScanningPushProtectionCustomLink { get; set; }

        /// <summary>
        /// Whether secret scanning push protection is automatically enabled for new repositories. Defaults to `False`.
        /// </summary>
        [Input("secretScanningPushProtectionEnabledForNewRepositories")]
        public Input<bool>? SecretScanningPushProtectionEnabledForNewRepositories { get; set; }

        /// <summary>
        /// Whether secret scanning validity checks are enabled. Defaults to `False`.
        /// </summary>
        [Input("secretScanningValidityChecksEnabled")]
        public Input<bool>? SecretScanningValidityChecksEnabled { get; set; }

        public EnterpriseSecurityAnalysisSettingsState()
        {
        }
        public static new EnterpriseSecurityAnalysisSettingsState Empty => new EnterpriseSecurityAnalysisSettingsState();
    }
}
