// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Github
{
    /// <summary>
    /// This resource allows you to manage GitHub Pages for a repository. See the
    /// [documentation](https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages)
    /// for details on GitHub Pages.
    /// 
    /// The authenticated user must be a repository administrator, maintainer, or have the 'manage GitHub Pages settings' permission. OAuth app tokens and personal access tokens (classic) need the repo scope to use this resource.
    /// 
    /// ## Example Usage
    /// 
    /// ### Legacy Build Type
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Github = Pulumi.Github;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var example = new Github.Index.Repository("example", new()
    ///     {
    ///         Name = "my-repo",
    ///         Visibility = "public",
    ///         AutoInit = true,
    ///     });
    /// 
    ///     var exampleRepositoryPages = new Github.Index.RepositoryPages("example", new()
    ///     {
    ///         Repository = example.Name,
    ///         BuildType = "legacy",
    ///         Source = new Github.Inputs.RepositoryPagesSourceArgs
    ///         {
    ///             Branch = "main",
    ///             Path = "/",
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ### Workflow Build Type (GitHub Actions)
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Github = Pulumi.Github;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var example = new Github.Index.Repository("example", new()
    ///     {
    ///         Name = "my-repo",
    ///         Visibility = "public",
    ///         AutoInit = true,
    ///     });
    /// 
    ///     var exampleRepositoryPages = new Github.Index.RepositoryPages("example", new()
    ///     {
    ///         Repository = example.Name,
    ///         BuildType = "workflow",
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ### With Custom Domain
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Github = Pulumi.Github;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var example = new Github.Index.Repository("example", new()
    ///     {
    ///         Name = "my-repo",
    ///         Visibility = "public",
    ///         AutoInit = true,
    ///     });
    /// 
    ///     var exampleRepositoryPages = new Github.Index.RepositoryPages("example", new()
    ///     {
    ///         Repository = example.Name,
    ///         BuildType = "legacy",
    ///         Cname = "example.com",
    ///         HttpsEnforced = true,
    ///         Source = new Github.Inputs.RepositoryPagesSourceArgs
    ///         {
    ///             Branch = "main",
    ///             Path = "/docs",
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// GitHub repository pages can be imported using the `repository-slug`, e.g.
    /// 
    /// ```sh
    /// $ pulumi import github:index/repositoryPages:RepositoryPages example my-repo
    /// ```
    /// </summary>
    [GithubResourceType("github:index/repositoryPages:RepositoryPages")]
    public partial class RepositoryPages : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The API URL of the GitHub Pages resource.
        /// </summary>
        [Output("apiUrl")]
        public Output<string> ApiUrl { get; private set; } = null!;

        /// <summary>
        /// The GitHub Pages site's build status (e.g., `Building` or `Built`).
        /// </summary>
        [Output("buildStatus")]
        public Output<string> BuildStatus { get; private set; } = null!;

        /// <summary>
        /// The type of GitHub Pages site to build. Can be `Legacy` or `Workflow`. Defaults to `Legacy`.
        /// </summary>
        [Output("buildType")]
        public Output<string?> BuildType { get; private set; } = null!;

        /// <summary>
        /// The custom domain for the repository.
        /// </summary>
        [Output("cname")]
        public Output<string?> Cname { get; private set; } = null!;

        /// <summary>
        /// Whether the rendered GitHub Pages site has a custom 404 page.
        /// </summary>
        [Output("custom404")]
        public Output<bool> Custom404 { get; private set; } = null!;

        /// <summary>
        /// The absolute URL (with scheme) to the rendered GitHub Pages site.
        /// </summary>
        [Output("htmlUrl")]
        public Output<string> HtmlUrl { get; private set; } = null!;

        /// <summary>
        /// Whether HTTPS is enforced for the GitHub Pages site. GitHub Pages sites serve over HTTPS by default; this setting only applies when a custom domain (`Cname`) is configured. Requires `Cname` to be set.
        /// </summary>
        [Output("httpsEnforced")]
        public Output<bool> HttpsEnforced { get; private set; } = null!;

        /// <summary>
        /// Whether the GitHub Pages site is public.
        /// </summary>
        [Output("public")]
        public Output<bool> Public { get; private set; } = null!;

        /// <summary>
        /// The repository name to configure GitHub Pages for.
        /// </summary>
        [Output("repository")]
        public Output<string> Repository { get; private set; } = null!;

        /// <summary>
        /// The ID of the repository.
        /// </summary>
        [Output("repositoryId")]
        public Output<int> RepositoryId { get; private set; } = null!;

        /// <summary>
        /// The source branch and directory for the rendered Pages site. Required when `BuildType` is `Legacy`. See Source below for details.
        /// </summary>
        [Output("source")]
        public Output<Outputs.RepositoryPagesSource?> Source { get; private set; } = null!;


        /// <summary>
        /// Create a RepositoryPages resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public RepositoryPages(string name, RepositoryPagesArgs args, CustomResourceOptions? options = null)
            : base("github:index/repositoryPages:RepositoryPages", name, args ?? new RepositoryPagesArgs(), MakeResourceOptions(options, ""))
        {
        }

        private RepositoryPages(string name, Input<string> id, RepositoryPagesState? state = null, CustomResourceOptions? options = null)
            : base("github:index/repositoryPages:RepositoryPages", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing RepositoryPages resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static RepositoryPages Get(string name, Input<string> id, RepositoryPagesState? state = null, CustomResourceOptions? options = null)
        {
            return new RepositoryPages(name, id, state, options);
        }
    }

    public sealed class RepositoryPagesArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The type of GitHub Pages site to build. Can be `Legacy` or `Workflow`. Defaults to `Legacy`.
        /// </summary>
        [Input("buildType")]
        public Input<string>? BuildType { get; set; }

        /// <summary>
        /// The custom domain for the repository.
        /// </summary>
        [Input("cname")]
        public Input<string>? Cname { get; set; }

        /// <summary>
        /// Whether HTTPS is enforced for the GitHub Pages site. GitHub Pages sites serve over HTTPS by default; this setting only applies when a custom domain (`Cname`) is configured. Requires `Cname` to be set.
        /// </summary>
        [Input("httpsEnforced")]
        public Input<bool>? HttpsEnforced { get; set; }

        /// <summary>
        /// Whether the GitHub Pages site is public.
        /// </summary>
        [Input("public")]
        public Input<bool>? Public { get; set; }

        /// <summary>
        /// The repository name to configure GitHub Pages for.
        /// </summary>
        [Input("repository", required: true)]
        public Input<string> Repository { get; set; } = null!;

        /// <summary>
        /// The source branch and directory for the rendered Pages site. Required when `BuildType` is `Legacy`. See Source below for details.
        /// </summary>
        [Input("source")]
        public Input<Inputs.RepositoryPagesSourceArgs>? Source { get; set; }

        public RepositoryPagesArgs()
        {
        }
        public static new RepositoryPagesArgs Empty => new RepositoryPagesArgs();
    }

    public sealed class RepositoryPagesState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The API URL of the GitHub Pages resource.
        /// </summary>
        [Input("apiUrl")]
        public Input<string>? ApiUrl { get; set; }

        /// <summary>
        /// The GitHub Pages site's build status (e.g., `Building` or `Built`).
        /// </summary>
        [Input("buildStatus")]
        public Input<string>? BuildStatus { get; set; }

        /// <summary>
        /// The type of GitHub Pages site to build. Can be `Legacy` or `Workflow`. Defaults to `Legacy`.
        /// </summary>
        [Input("buildType")]
        public Input<string>? BuildType { get; set; }

        /// <summary>
        /// The custom domain for the repository.
        /// </summary>
        [Input("cname")]
        public Input<string>? Cname { get; set; }

        /// <summary>
        /// Whether the rendered GitHub Pages site has a custom 404 page.
        /// </summary>
        [Input("custom404")]
        public Input<bool>? Custom404 { get; set; }

        /// <summary>
        /// The absolute URL (with scheme) to the rendered GitHub Pages site.
        /// </summary>
        [Input("htmlUrl")]
        public Input<string>? HtmlUrl { get; set; }

        /// <summary>
        /// Whether HTTPS is enforced for the GitHub Pages site. GitHub Pages sites serve over HTTPS by default; this setting only applies when a custom domain (`Cname`) is configured. Requires `Cname` to be set.
        /// </summary>
        [Input("httpsEnforced")]
        public Input<bool>? HttpsEnforced { get; set; }

        /// <summary>
        /// Whether the GitHub Pages site is public.
        /// </summary>
        [Input("public")]
        public Input<bool>? Public { get; set; }

        /// <summary>
        /// The repository name to configure GitHub Pages for.
        /// </summary>
        [Input("repository")]
        public Input<string>? Repository { get; set; }

        /// <summary>
        /// The ID of the repository.
        /// </summary>
        [Input("repositoryId")]
        public Input<int>? RepositoryId { get; set; }

        /// <summary>
        /// The source branch and directory for the rendered Pages site. Required when `BuildType` is `Legacy`. See Source below for details.
        /// </summary>
        [Input("source")]
        public Input<Inputs.RepositoryPagesSourceGetArgs>? Source { get; set; }

        public RepositoryPagesState()
        {
        }
        public static new RepositoryPagesState Empty => new RepositoryPagesState();
    }
}
