// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System.Collections.Immutable;

namespace Pulumi.Github
{
    public static class Config
    {
        private static readonly Pulumi.Config __config = new Pulumi.Config("github");
        /// <summary>
        /// Authenticate without a token. When `anonymous`is true, the provider will not be able to access resourcesthat require
        /// authentication.
        /// </summary>
        public static bool? Anonymous { get; set; } = __config.GetBoolean("anonymous");

        /// <summary>
        /// The GitHub Base API URL
        /// </summary>
        public static string? BaseUrl { get; set; } = __config.Get("baseUrl");

        /// <summary>
        /// Run outside an organization. When `individual`is true, the provider will run outside the scope of anorganization.
        /// </summary>
        public static bool? Individual { get; set; } = __config.GetBoolean("individual");

        /// <summary>
        /// Whether server should be accessed without verifying the TLS certificate.
        /// </summary>
        public static bool? Insecure { get; set; } = __config.GetBoolean("insecure");

        /// <summary>
        /// The GitHub organization name to manage. If `individual` is false, `organization` is required.
        /// </summary>
        public static string? Organization { get; set; } = __config.Get("organization");

        /// <summary>
        /// The OAuth token used to connect to GitHub. If `anonymous` is false, `token` is required.
        /// </summary>
        public static string? Token { get; set; } = __config.Get("token");

    }
}
