// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.github.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetCollaboratorsPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetCollaboratorsPlainArgs Empty = new GetCollaboratorsPlainArgs();

    @Import(name="affiliation")
    private @Nullable String affiliation;

    public Optional<String> affiliation() {
        return Optional.ofNullable(this.affiliation);
    }

    @Import(name="owner", required=true)
    private String owner;

    public String owner() {
        return this.owner;
    }

    @Import(name="repository", required=true)
    private String repository;

    public String repository() {
        return this.repository;
    }

    private GetCollaboratorsPlainArgs() {}

    private GetCollaboratorsPlainArgs(GetCollaboratorsPlainArgs $) {
        this.affiliation = $.affiliation;
        this.owner = $.owner;
        this.repository = $.repository;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetCollaboratorsPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetCollaboratorsPlainArgs $;

        public Builder() {
            $ = new GetCollaboratorsPlainArgs();
        }

        public Builder(GetCollaboratorsPlainArgs defaults) {
            $ = new GetCollaboratorsPlainArgs(Objects.requireNonNull(defaults));
        }

        public Builder affiliation(@Nullable String affiliation) {
            $.affiliation = affiliation;
            return this;
        }

        public Builder owner(String owner) {
            $.owner = owner;
            return this;
        }

        public Builder repository(String repository) {
            $.repository = repository;
            return this;
        }

        public GetCollaboratorsPlainArgs build() {
            $.owner = Objects.requireNonNull($.owner, "expected parameter 'owner' to be non-null");
            $.repository = Objects.requireNonNull($.repository, "expected parameter 'repository' to be non-null");
            return $;
        }
    }

}
