// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.github.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;


public final class GetOrganizationPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetOrganizationPlainArgs Empty = new GetOrganizationPlainArgs();

    /**
     * The name of the organization account
     * 
     */
    @Import(name="name", required=true)
    private String name;

    /**
     * @return The name of the organization account
     * 
     */
    public String name() {
        return this.name;
    }

    private GetOrganizationPlainArgs() {}

    private GetOrganizationPlainArgs(GetOrganizationPlainArgs $) {
        this.name = $.name;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetOrganizationPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetOrganizationPlainArgs $;

        public Builder() {
            $ = new GetOrganizationPlainArgs();
        }

        public Builder(GetOrganizationPlainArgs defaults) {
            $ = new GetOrganizationPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param name The name of the organization account
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            $.name = name;
            return this;
        }

        public GetOrganizationPlainArgs build() {
            $.name = Objects.requireNonNull($.name, "expected parameter 'name' to be non-null");
            return $;
        }
    }

}
