// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.github.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetRepositoryEnvironmentDeploymentPoliciesArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetRepositoryEnvironmentDeploymentPoliciesArgs Empty = new GetRepositoryEnvironmentDeploymentPoliciesArgs();

    /**
     * Name of the environment to retrieve the deployment branch policies from.
     * 
     */
    @Import(name="environment", required=true)
    private Output<String> environment;

    /**
     * @return Name of the environment to retrieve the deployment branch policies from.
     * 
     */
    public Output<String> environment() {
        return this.environment;
    }

    /**
     * Name of the repository to retrieve the deployment branch policies from.
     * 
     */
    @Import(name="repository", required=true)
    private Output<String> repository;

    /**
     * @return Name of the repository to retrieve the deployment branch policies from.
     * 
     */
    public Output<String> repository() {
        return this.repository;
    }

    private GetRepositoryEnvironmentDeploymentPoliciesArgs() {}

    private GetRepositoryEnvironmentDeploymentPoliciesArgs(GetRepositoryEnvironmentDeploymentPoliciesArgs $) {
        this.environment = $.environment;
        this.repository = $.repository;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetRepositoryEnvironmentDeploymentPoliciesArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetRepositoryEnvironmentDeploymentPoliciesArgs $;

        public Builder() {
            $ = new GetRepositoryEnvironmentDeploymentPoliciesArgs();
        }

        public Builder(GetRepositoryEnvironmentDeploymentPoliciesArgs defaults) {
            $ = new GetRepositoryEnvironmentDeploymentPoliciesArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param environment Name of the environment to retrieve the deployment branch policies from.
         * 
         * @return builder
         * 
         */
        public Builder environment(Output<String> environment) {
            $.environment = environment;
            return this;
        }

        /**
         * @param environment Name of the environment to retrieve the deployment branch policies from.
         * 
         * @return builder
         * 
         */
        public Builder environment(String environment) {
            return environment(Output.of(environment));
        }

        /**
         * @param repository Name of the repository to retrieve the deployment branch policies from.
         * 
         * @return builder
         * 
         */
        public Builder repository(Output<String> repository) {
            $.repository = repository;
            return this;
        }

        /**
         * @param repository Name of the repository to retrieve the deployment branch policies from.
         * 
         * @return builder
         * 
         */
        public Builder repository(String repository) {
            return repository(Output.of(repository));
        }

        public GetRepositoryEnvironmentDeploymentPoliciesArgs build() {
            if ($.environment == null) {
                throw new MissingRequiredPropertyException("GetRepositoryEnvironmentDeploymentPoliciesArgs", "environment");
            }
            if ($.repository == null) {
                throw new MissingRequiredPropertyException("GetRepositoryEnvironmentDeploymentPoliciesArgs", "repository");
            }
            return $;
        }
    }

}
