// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.github.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetAppTokenResult {
    private String appId;
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;
    private String installationId;
    private String pemFile;
    /**
     * @return The generated GitHub APP JWT.
     * 
     */
    private String token;

    private GetAppTokenResult() {}
    public String appId() {
        return this.appId;
    }
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    public String installationId() {
        return this.installationId;
    }
    public String pemFile() {
        return this.pemFile;
    }
    /**
     * @return The generated GitHub APP JWT.
     * 
     */
    public String token() {
        return this.token;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetAppTokenResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String appId;
        private String id;
        private String installationId;
        private String pemFile;
        private String token;
        public Builder() {}
        public Builder(GetAppTokenResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.appId = defaults.appId;
    	      this.id = defaults.id;
    	      this.installationId = defaults.installationId;
    	      this.pemFile = defaults.pemFile;
    	      this.token = defaults.token;
        }

        @CustomType.Setter
        public Builder appId(String appId) {
            this.appId = Objects.requireNonNull(appId);
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }
        @CustomType.Setter
        public Builder installationId(String installationId) {
            this.installationId = Objects.requireNonNull(installationId);
            return this;
        }
        @CustomType.Setter
        public Builder pemFile(String pemFile) {
            this.pemFile = Objects.requireNonNull(pemFile);
            return this;
        }
        @CustomType.Setter
        public Builder token(String token) {
            this.token = Objects.requireNonNull(token);
            return this;
        }
        public GetAppTokenResult build() {
            final var _resultValue = new GetAppTokenResult();
            _resultValue.appId = appId;
            _resultValue.id = id;
            _resultValue.installationId = installationId;
            _resultValue.pemFile = pemFile;
            _resultValue.token = token;
            return _resultValue;
        }
    }
}
