// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.github.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.github.outputs.GetRepositoryPullRequestsResult;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetRepositoryPullRequestsInvokeResult {
    /**
     * @return Name of the ref (branch) of the Pull Request base.
     * 
     */
    private @Nullable String baseRef;
    private String baseRepository;
    /**
     * @return Value of the Pull Request `HEAD` reference.
     * 
     */
    private @Nullable String headRef;
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;
    private @Nullable String owner;
    /**
     * @return Collection of Pull Requests matching the filters. Each of the results conforms to the following scheme:
     * 
     */
    private List<GetRepositoryPullRequestsResult> results;
    private @Nullable String sortBy;
    private @Nullable String sortDirection;
    /**
     * @return the current Pull Request state - can be &#34;open&#34;, &#34;closed&#34; or &#34;merged&#34;.
     * 
     */
    private @Nullable String state;

    private GetRepositoryPullRequestsInvokeResult() {}
    /**
     * @return Name of the ref (branch) of the Pull Request base.
     * 
     */
    public Optional<String> baseRef() {
        return Optional.ofNullable(this.baseRef);
    }
    public String baseRepository() {
        return this.baseRepository;
    }
    /**
     * @return Value of the Pull Request `HEAD` reference.
     * 
     */
    public Optional<String> headRef() {
        return Optional.ofNullable(this.headRef);
    }
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    public Optional<String> owner() {
        return Optional.ofNullable(this.owner);
    }
    /**
     * @return Collection of Pull Requests matching the filters. Each of the results conforms to the following scheme:
     * 
     */
    public List<GetRepositoryPullRequestsResult> results() {
        return this.results;
    }
    public Optional<String> sortBy() {
        return Optional.ofNullable(this.sortBy);
    }
    public Optional<String> sortDirection() {
        return Optional.ofNullable(this.sortDirection);
    }
    /**
     * @return the current Pull Request state - can be &#34;open&#34;, &#34;closed&#34; or &#34;merged&#34;.
     * 
     */
    public Optional<String> state() {
        return Optional.ofNullable(this.state);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetRepositoryPullRequestsInvokeResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String baseRef;
        private String baseRepository;
        private @Nullable String headRef;
        private String id;
        private @Nullable String owner;
        private List<GetRepositoryPullRequestsResult> results;
        private @Nullable String sortBy;
        private @Nullable String sortDirection;
        private @Nullable String state;
        public Builder() {}
        public Builder(GetRepositoryPullRequestsInvokeResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.baseRef = defaults.baseRef;
    	      this.baseRepository = defaults.baseRepository;
    	      this.headRef = defaults.headRef;
    	      this.id = defaults.id;
    	      this.owner = defaults.owner;
    	      this.results = defaults.results;
    	      this.sortBy = defaults.sortBy;
    	      this.sortDirection = defaults.sortDirection;
    	      this.state = defaults.state;
        }

        @CustomType.Setter
        public Builder baseRef(@Nullable String baseRef) {

            this.baseRef = baseRef;
            return this;
        }
        @CustomType.Setter
        public Builder baseRepository(String baseRepository) {
            if (baseRepository == null) {
              throw new MissingRequiredPropertyException("GetRepositoryPullRequestsInvokeResult", "baseRepository");
            }
            this.baseRepository = baseRepository;
            return this;
        }
        @CustomType.Setter
        public Builder headRef(@Nullable String headRef) {

            this.headRef = headRef;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetRepositoryPullRequestsInvokeResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder owner(@Nullable String owner) {

            this.owner = owner;
            return this;
        }
        @CustomType.Setter
        public Builder results(List<GetRepositoryPullRequestsResult> results) {
            if (results == null) {
              throw new MissingRequiredPropertyException("GetRepositoryPullRequestsInvokeResult", "results");
            }
            this.results = results;
            return this;
        }
        public Builder results(GetRepositoryPullRequestsResult... results) {
            return results(List.of(results));
        }
        @CustomType.Setter
        public Builder sortBy(@Nullable String sortBy) {

            this.sortBy = sortBy;
            return this;
        }
        @CustomType.Setter
        public Builder sortDirection(@Nullable String sortDirection) {

            this.sortDirection = sortDirection;
            return this;
        }
        @CustomType.Setter
        public Builder state(@Nullable String state) {

            this.state = state;
            return this;
        }
        public GetRepositoryPullRequestsInvokeResult build() {
            final var _resultValue = new GetRepositoryPullRequestsInvokeResult();
            _resultValue.baseRef = baseRef;
            _resultValue.baseRepository = baseRepository;
            _resultValue.headRef = headRef;
            _resultValue.id = id;
            _resultValue.owner = owner;
            _resultValue.results = results;
            _resultValue.sortBy = sortBy;
            _resultValue.sortDirection = sortDirection;
            _resultValue.state = state;
            return _resultValue;
        }
    }
}
