// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.github.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.github.outputs.RepositoryRulesetConditionsRefName;
import java.util.Objects;

@CustomType
public final class RepositoryRulesetConditions {
    /**
     * @return (Block List, Min: 1, Max: 1) (see below for nested schema)
     * 
     */
    private RepositoryRulesetConditionsRefName refName;

    private RepositoryRulesetConditions() {}
    /**
     * @return (Block List, Min: 1, Max: 1) (see below for nested schema)
     * 
     */
    public RepositoryRulesetConditionsRefName refName() {
        return this.refName;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(RepositoryRulesetConditions defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private RepositoryRulesetConditionsRefName refName;
        public Builder() {}
        public Builder(RepositoryRulesetConditions defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.refName = defaults.refName;
        }

        @CustomType.Setter
        public Builder refName(RepositoryRulesetConditionsRefName refName) {
            this.refName = Objects.requireNonNull(refName);
            return this;
        }
        public RepositoryRulesetConditions build() {
            final var o = new RepositoryRulesetConditions();
            o.refName = refName;
            return o;
        }
    }
}
