# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetOrganizationRolesResult',
    'AwaitableGetOrganizationRolesResult',
    'get_organization_roles',
    'get_organization_roles_output',
]

@pulumi.output_type
class GetOrganizationRolesResult:
    """
    A collection of values returned by getOrganizationRoles.
    """
    def __init__(__self__, id=None, roles=None):
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if roles and not isinstance(roles, list):
            raise TypeError("Expected argument 'roles' to be a list")
        pulumi.set(__self__, "roles", roles)

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def roles(self) -> Sequence['outputs.GetOrganizationRolesRoleResult']:
        """
        (Set of Object, see schema) Available organization roles.
        """
        return pulumi.get(self, "roles")


class AwaitableGetOrganizationRolesResult(GetOrganizationRolesResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetOrganizationRolesResult(
            id=self.id,
            roles=self.roles)


def get_organization_roles(opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetOrganizationRolesResult:
    """
    Lookup all custom roles in an organization.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_github as github

    example = github.get_organization_roles()
    ```

    ## Nested Schema for `roles`

    ### Read-Only

    - `role_id` (Number) The ID of the organization role.
    - `name` (String) The name of the organization role.
    - `description` (String) The description of the organization role.
    - `source` (String) The source of this role; one of `Predefined`, `Organization`, or `Enterprise`.
    - `base_role` (String) The system role from which this role inherits permissions.
    - `permissions` (Set of String) The permissions included in this role.
    """
    __args__ = dict()
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('github:index/getOrganizationRoles:getOrganizationRoles', __args__, opts=opts, typ=GetOrganizationRolesResult).value

    return AwaitableGetOrganizationRolesResult(
        id=pulumi.get(__ret__, 'id'),
        roles=pulumi.get(__ret__, 'roles'))
def get_organization_roles_output(opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetOrganizationRolesResult]:
    """
    Lookup all custom roles in an organization.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_github as github

    example = github.get_organization_roles()
    ```

    ## Nested Schema for `roles`

    ### Read-Only

    - `role_id` (Number) The ID of the organization role.
    - `name` (String) The name of the organization role.
    - `description` (String) The description of the organization role.
    - `source` (String) The source of this role; one of `Predefined`, `Organization`, or `Enterprise`.
    - `base_role` (String) The system role from which this role inherits permissions.
    - `permissions` (Set of String) The permissions included in this role.
    """
    __args__ = dict()
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('github:index/getOrganizationRoles:getOrganizationRoles', __args__, opts=opts, typ=GetOrganizationRolesResult)
    return __ret__.apply(lambda __response__: GetOrganizationRolesResult(
        id=pulumi.get(__response__, 'id'),
        roles=pulumi.get(__response__, 'roles')))
