// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Github.Inputs
{

    public sealed class IssueLabelsLabelArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// A 6 character hex code, **without the leading #**, identifying the color of the label.
        /// </summary>
        [Input("color", required: true)]
        public Input<string> Color { get; set; } = null!;

        /// <summary>
        /// A short description of the label.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The name of the label.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// The URL to the issue label
        /// </summary>
        [Input("url")]
        public Input<string>? Url { get; set; }

        public IssueLabelsLabelArgs()
        {
        }
        public static new IssueLabelsLabelArgs Empty => new IssueLabelsLabelArgs();
    }
}
