// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Github.Inputs
{

    public sealed class RepositoryRulesetRulesFileExtensionRestrictionArgs : global::Pulumi.ResourceArgs
    {
        [Input("restrictedFileExtensions", required: true)]
        private InputList<string>? _restrictedFileExtensions;

        /// <summary>
        /// A list of file extensions.
        /// </summary>
        public InputList<string> RestrictedFileExtensions
        {
            get => _restrictedFileExtensions ?? (_restrictedFileExtensions = new InputList<string>());
            set => _restrictedFileExtensions = value;
        }

        public RepositoryRulesetRulesFileExtensionRestrictionArgs()
        {
        }
        public static new RepositoryRulesetRulesFileExtensionRestrictionArgs Empty => new RepositoryRulesetRulesFileExtensionRestrictionArgs();
    }
}
