// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.github;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.github.DependabotSecretArgs;
import com.pulumi.github.Utilities;
import com.pulumi.github.inputs.DependabotSecretState;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * ## Import
 * 
 * ### Import Command
 * 
 * The following command imports a GitHub Dependabot secret named `mysecret` for the repo `myrepo` to a `github_dependabot_secret` resource named `example`.
 * 
 * ```sh
 * $ pulumi import github:index/dependabotSecret:DependabotSecret example myrepo:mysecret
 * ```
 * 
 */
@ResourceType(type="github:index/dependabotSecret:DependabotSecret")
public class DependabotSecret extends com.pulumi.resources.CustomResource {
    /**
     * Date the secret was created.
     * 
     */
    @Export(name="createdAt", refs={String.class}, tree="[0]")
    private Output<String> createdAt;

    /**
     * @return Date the secret was created.
     * 
     */
    public Output<String> createdAt() {
        return this.createdAt;
    }
    /**
     * Encrypted value of the secret using the GitHub public key in Base64 format.
     * 
     */
    @Export(name="encryptedValue", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> encryptedValue;

    /**
     * @return Encrypted value of the secret using the GitHub public key in Base64 format.
     * 
     */
    public Output<Optional<String>> encryptedValue() {
        return Codegen.optional(this.encryptedValue);
    }
    /**
     * ID of the public key used to encrypt the secret. This should be provided when setting `encryptedValue`; if it isn&#39;t then the current public key will be looked up, which could cause a missmatch. This conflicts with `plaintextValue`.
     * 
     */
    @Export(name="keyId", refs={String.class}, tree="[0]")
    private Output<String> keyId;

    /**
     * @return ID of the public key used to encrypt the secret. This should be provided when setting `encryptedValue`; if it isn&#39;t then the current public key will be looked up, which could cause a missmatch. This conflicts with `plaintextValue`.
     * 
     */
    public Output<String> keyId() {
        return this.keyId;
    }
    /**
     * Plaintext value of the secret to be encrypted.
     * 
     * &gt; **Note**: One of either `encryptedValue` or `plaintextValue` must be specified.
     * 
     */
    @Export(name="plaintextValue", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> plaintextValue;

    /**
     * @return Plaintext value of the secret to be encrypted.
     * 
     * &gt; **Note**: One of either `encryptedValue` or `plaintextValue` must be specified.
     * 
     */
    public Output<Optional<String>> plaintextValue() {
        return Codegen.optional(this.plaintextValue);
    }
    /**
     * Date the secret was last updated in GitHub.
     * 
     */
    @Export(name="remoteUpdatedAt", refs={String.class}, tree="[0]")
    private Output<String> remoteUpdatedAt;

    /**
     * @return Date the secret was last updated in GitHub.
     * 
     */
    public Output<String> remoteUpdatedAt() {
        return this.remoteUpdatedAt;
    }
    /**
     * Name of the repository.
     * 
     */
    @Export(name="repository", refs={String.class}, tree="[0]")
    private Output<String> repository;

    /**
     * @return Name of the repository.
     * 
     */
    public Output<String> repository() {
        return this.repository;
    }
    /**
     * ID of the repository.
     * 
     */
    @Export(name="repositoryId", refs={Integer.class}, tree="[0]")
    private Output<Integer> repositoryId;

    /**
     * @return ID of the repository.
     * 
     */
    public Output<Integer> repositoryId() {
        return this.repositoryId;
    }
    /**
     * Name of the secret.
     * 
     */
    @Export(name="secretName", refs={String.class}, tree="[0]")
    private Output<String> secretName;

    /**
     * @return Name of the secret.
     * 
     */
    public Output<String> secretName() {
        return this.secretName;
    }
    /**
     * Date the secret was last updated by the provider.
     * 
     */
    @Export(name="updatedAt", refs={String.class}, tree="[0]")
    private Output<String> updatedAt;

    /**
     * @return Date the secret was last updated by the provider.
     * 
     */
    public Output<String> updatedAt() {
        return this.updatedAt;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public DependabotSecret(java.lang.String name) {
        this(name, DependabotSecretArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public DependabotSecret(java.lang.String name, DependabotSecretArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public DependabotSecret(java.lang.String name, DependabotSecretArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("github:index/dependabotSecret:DependabotSecret", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private DependabotSecret(java.lang.String name, Output<java.lang.String> id, @Nullable DependabotSecretState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("github:index/dependabotSecret:DependabotSecret", name, state, makeResourceOptions(options, id), false);
    }

    private static DependabotSecretArgs makeArgs(DependabotSecretArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? DependabotSecretArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .additionalSecretOutputs(List.of(
                "encryptedValue",
                "plaintextValue"
            ))
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static DependabotSecret get(java.lang.String name, Output<java.lang.String> id, @Nullable DependabotSecretState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new DependabotSecret(name, id, state, options);
    }
}
